# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jesus Tordesillas Torres
repository: jtorde/jtorde.github.io
email: jtorde@mit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal webpage of Jesus Tordesillas Torres.
twitter_username: username
github_username: jtorde
minimal_mistakes_skin: default
#search: true

#This next line needs to be commented for github.io
# baseurl: /~jtorde #For MIT website. (url will then be mit.edu/~jtorde)

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-scholar

author:
  name   : "Jesus Tordesillas Torres"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Postdoctoral Associate at the Aerospace Controls Lab at MIT"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jtorde"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jesus-tordesillas-torres/"
    - label: "Google Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=QKcwqsQAAAAJ&hl=en&oi=sra"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jtorde"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jesus-tordesillas-torres/"
    - label: "Google Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=QKcwqsQAAAAJ&hl=en&oi=sra"

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: splash
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
